### ISSUE TITLE
Inconsistency between the implementation and the explanation for B.3b

### ISSUE THREAD

**Issue by yudai-kato-aisin** [scomup/simple_gaussian_splatting#2]
I would like to ask a question about the difference between $`\diff{M}{p_c}`$ in `backward.pdf` and the implementation in `kernel.cu` [#L525-L530](https://github.com/scomup/EasyGaussianSplatting/blob/main/gsplatcu/kernel.cu#L525-L530).

As far as I have verifiied `backward.pdf` seems to be correct but the implementation is different from it.
The matrix looks different in the  $`\diff{M}{x}`$

**Comment by scomup** [comment]
Thank you for pointing it out.

Actually, the implementation is correct. The $\frac{\partial M}{\partial p_c}$ in `backward.pdf` is incorrect.

I think you believe the `backward.pdf` version is correct because the $J$ (F.3.6) in `forward.pdf` is also incorrect due to my typo.

The errors have been fixed in a recent commit.

**Comment by yudai-kato-aisin** [comment]
Thank you for correcting the document.
